Algoritmo "Cálculo da idade"
// Descrição   : algoritmo que o usuário iforma o ano de nascimento e devolve//
// a idade da pessoa. O mês nã deverá ser considerado//
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/10/2025
Var
anoatual: inteiro
anonascimento: inteiro
idade: inteiro

Inicio
      Escreval("Qual o ano atual?")
      Leia(anoatual)
      Escreval("Qual o ano de nascimento?")
      Leia (anonascimento)
      idade<- anoatual - anonascimento
      Escreval("sua idade é: " , idade)


Fimalgoritmo